packages:
  - packages/*

catalog:
  '@graphql-codegen/cli': 6.0.0
  '@parcel/watcher': 2.5.1
  '@types/node': 24.5.2
  graphql: 16.11.0
  lucuma-core: 0.146.0
  lucuma-schemas: 0.173.0
  navigate-server-schema: 0.1.0-20250930-444ae729
  typescript: 5.9.2

injectWorkspacePackages: true
