packages:
  - packages/*

catalog:
  '@graphql-codegen/cli': 6.0.0
  '@parcel/watcher': 2.5.1
  '@types/node': 24.8.1
  graphql: 16.11.0
  lucuma-core: 0.148.0
  lucuma-schemas: 0.177.0-20251016-a7d3e3f6
  typescript: 5.9.3

injectWorkspacePackages: true
