packages:
  - packages/*

catalog:
  '@graphql-codegen/cli': 6.0.2
  '@parcel/watcher': 2.5.1
  '@types/node': 24.10.1
  graphql: 16.12.0
  lucuma-core: 0.155.0
  lucuma-schemas: 0.177.0-20251119-e3a25cbc
  typescript: 5.9.3

injectWorkspacePackages: true
