packages:
  - packages/*

catalog:
  '@graphql-codegen/cli': 6.0.1
  '@parcel/watcher': 2.5.1
  '@types/node': 24.9.2
  graphql: 16.12.0
  lucuma-core: 0.153.0
  lucuma-schemas: 0.177.0-20251103-099cde97
  typescript: 5.9.3

injectWorkspacePackages: true
