packages:
  - packages/*

catalog:
  '@graphql-codegen/cli': 6.0.1
  '@parcel/watcher': 2.5.1
  '@types/node': 24.9.2
  graphql: 16.11.0
  lucuma-core: 0.151.0
  lucuma-schemas: 0.177.0-20251031-d056a598
  typescript: 5.9.3

injectWorkspacePackages: true
