packages:
  - packages/*

catalog:
  graphql: 16.11.0
  '@types/node': 24.1.0
  '@graphql-codegen/cli': 5.0.7
  '@parcel/watcher': 2.5.1
  lucuma-core: 0.138.0
  lucuma-schemas: 0.149.1
  navigate-server-schema: 0.1.0-20250718-e638d465
  typescript: 5.8.3

injectWorkspacePackages: true
