packages:
  - packages/*

catalog:
  graphql: 16.11.0
  '@graphql-codegen/cli': 5.0.7
  '@parcel/watcher': 2.5.1
  lucuma-core: 0.136.3
  lucuma-schemas: 0.144.0
  navigate-server-schema: 0.1.0-20250710-17592907
  typescript: 5.8.3

injectWorkspacePackages: true
