import type { Prisma } from '../../gen/client.ts';

export const INITIAL_CAL_PARAMS: Prisma.CalParamsCreateInput[] = [
  {
    site: 'GN',
    acqCamX: 518,
    acqCamY: 550,
    baffleVisible: 1.05,
    baffleNearIR: 3,
    topShutterCurrentLimit: 27,
    bottomShutterCurrentLimit: 32,
    pwfs1CenterX: 2.324,
    pwfs1CenterY: -12.213,
    pwfs1CenterZ: 0,
    pwfs2CenterX: -3.493,
    pwfs2CenterY: -2.48,
    pwfs2CenterZ: 0,
    defocusEnabled: true,
    gmosSfoDefocus: 90,
    gnirsSfoDefocus: 30,
    gnirsP1Defocus: 3.7,
    gmosP1Defocus: -7,
    gmosOiDefocus: 0,
    comment: 'Initial CalParams for GN',
  },
  {
    site: 'GS',
    acqCamX: 449,
    acqCamY: 522,
    baffleVisible: 1.0,
    baffleNearIR: 1.0,
    topShutterCurrentLimit: 30,
    bottomShutterCurrentLimit: 30,
    pwfs1CenterX: 0.101,
    pwfs1CenterY: -15.076,
    pwfs1CenterZ: 0,
    pwfs2CenterX: -2.216,
    pwfs2CenterY: -2.76,
    pwfs2CenterZ: 0,
    defocusEnabled: false,
    gmosSfoDefocus: null,
    gnirsSfoDefocus: null,
    gnirsP1Defocus: null,
    gmosP1Defocus: null,
    gmosOiDefocus: null,
    comment: 'Initial CalParams for GS',
  },
];
