# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Navigate UI - CI

on:
  push:
    branches: ['main']
    tags: ['v*']
  pull_request:
    branches: ['main']

env:
  FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w ui exec playwright install chromium
      - run: pnpm -r codegen --check
      - run: pnpm -r build
      - run: pnpm lint
      - run: pnpm -r test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: |
            dist
            !dist/**/*.md
      - name: Run BundleMon
        continue-on-error: true
        uses: lironer/bundlemon-action@v1
        with:
          working-directory: 'packages/ui'

  publish:
    name: Publish Artifacts
    needs: [build]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - run: pnpm -r build

      - name: Build and publish docker image
        # TODO
        run: exit 1
