name: Test deploy

on:
  push:
    branches: ['*']

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_USERNAME: 'nlsoftware'
      REGISTRY_IMAGE: noirlab/gpp-nav
      HEROKU_APP_NAME: navigate-dev-gn
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          docker pull ${{ env.REGISTRY_IMAGE }}

          docker tag ${{ env.REGISTRY_IMAGE }} registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web
          heroku container:release web -a ${{ env.HEROKU_APP_NAME }} -v
